### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by aradhyamathur** [Ben-Louis/Deep-Image-Analogy-PyTorch#10]
Unable  to access the model url in VGG19.py. "https://s3-us-west-2.amazonaws.com/jcjohns-models/vgg19-d01eb7cb.pth" seems to be forbidden can you please check or suggest alternate.

**Comment by ahmetgunduz** [comment]
@aradhyamathur  try this path : https://download.pytorch.org/models/vgg19-dcbb9e9d.pth

**Comment by Ben-Louis** [comment]
I have updated the url to "https://web.eecs.umich.edu/~justincj/models/vgg19-d01eb7cb.pth". 
@ahmetgunduz  The official pretrained model from pytorch will generate weird results even with correct preprocessing. 
Examples:
![img_AP](https://user-images.githubusercontent.com/26127467/144540278-95410f7c-dec4-496d-b05d-34d053dad900.png)
![img_B](https://user-images.githubusercontent.com/26127467/144540281-db16ca63-8683-4bd5-acd4-25103a6be1a1.png)
