### ISSUE TITLE
/libmkl_core.so: invalid ELF header

### ISSUE THREAD

**Issue by antonkulaga** [Ben-Louis/Deep-Image-Analogy-PyTorch#8]
I cannot run it at all! I tried different versions of py-torch and cuda, but I keep getting ELF header error. My OS is latest Ubuntu (just in case).
```
ImportError: /data/miniconda3/envs/analogy4/lib/python3.6/site-packages/torch/lib/../../../../libmkl_core.so: invalid ELF header
```

**Comment by antonkulaga** [comment]
Looks like I resolved it. Will make a PR with environment.yml

**Comment by sameerCoder** [comment]
Hi Antonkulaga , 
How to solve this ELF header issue , please let me know as i am also facing same issue.

**Comment by CrystalGuo0312** [comment]
Hi Antonkulaga ,
I meet the same problem, could you tell me how to resolve it ? Thanks a lot.

**Comment by amirakbarnejad** [comment]
In my case installing mkl solved the problem:
conda install -c anaconda mkl
